create table dim_date(
dim_date_id INTEGER GENERATED by default on null as identity not null primary key,
date_value date not null,
day_number_of_year integer not null,
day_number_of_month integer not null,
day_number_of_week integer not null,
day_name_english varchar(20) not null,
day_name_polish varchar(20) not null,
month_number_of_year integer not null,
month_name_english varchar(20) not null,
month_name_polish varchar(20) not null,
calendar_quarter varchar(2) not null,
year_number integer not null
);

alter session set nls_territory = "UNITED KINGDOM";

INSERT INTO dim_date (date_value,
day_number_of_year,
day_number_of_month,
day_number_of_week,
day_name_english,
day_name_polish,
month_number_of_year,
month_name_english,
month_name_polish,
calendar_quarter,
year_number
) select ORDERDATE as date_value, 
        TO_CHAR(ORDERDATE, 'DDD') as day_number_of_year, 
        TO_CHAR(ORDERDATE, 'DD') as day_number_of_month, 
        TO_CHAR(ORDERDATE, 'D') as day_number_of_week,
        TO_CHAR(ORDERDATE, 'Day') as day_name_english,
        TO_CHAR(ORDERDATE, 'Day', 'NLS_DATE_LANGUAGE = POLISH') as day_name_polish,
        TO_CHAR(ORDERDATE, 'MM') as month_number_of_year,
        TO_CHAR(ORDERDATE, 'Month') as month_name_english,
        TO_CHAR(ORDERDATE, 'Month', 'NLS_DATE_LANGUAGE = POLISH') as month_name_polish,
        TO_CHAR(ORDERDATE, 'Q') as calendar_quarter,
        TO_CHAR(ORDERDATE, 'YYYY') as year_number
        from SALESORDERDETAIL;
        